# title: SDK Documentation
logo: "/assets/images/lofelt-logo-rgb-white.svg"
search_enabled: true
plugins:
  - jekyll-relative-links
remote_theme: pmarsceill/just-the-docs
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
aux_links:
  "Get Support":
    - "https://testcustomerfeedback.atlassian.net/servicedesk/customer/portal/1"
